require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RaftChecksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # RaftCheck. As you add validations to RaftCheck, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RaftChecksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all raft_checks as @raft_checks" do
      raft_check = RaftCheck.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:raft_checks)).to eq([raft_check])
    end
  end

  describe "GET show" do
    it "assigns the requested raft_check as @raft_check" do
      raft_check = RaftCheck.create! valid_attributes
      get :show, {:id => raft_check.to_param}, valid_session
      expect(assigns(:raft_check)).to eq(raft_check)
    end
  end

  describe "GET new" do
    it "assigns a new raft_check as @raft_check" do
      get :new, {}, valid_session
      expect(assigns(:raft_check)).to be_a_new(RaftCheck)
    end
  end

  describe "GET edit" do
    it "assigns the requested raft_check as @raft_check" do
      raft_check = RaftCheck.create! valid_attributes
      get :edit, {:id => raft_check.to_param}, valid_session
      expect(assigns(:raft_check)).to eq(raft_check)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RaftCheck" do
        expect {
          post :create, {:raft_check => valid_attributes}, valid_session
        }.to change(RaftCheck, :count).by(1)
      end

      it "assigns a newly created raft_check as @raft_check" do
        post :create, {:raft_check => valid_attributes}, valid_session
        expect(assigns(:raft_check)).to be_a(RaftCheck)
        expect(assigns(:raft_check)).to be_persisted
      end

      it "redirects to the created raft_check" do
        post :create, {:raft_check => valid_attributes}, valid_session
        expect(response).to redirect_to(RaftCheck.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved raft_check as @raft_check" do
        post :create, {:raft_check => invalid_attributes}, valid_session
        expect(assigns(:raft_check)).to be_a_new(RaftCheck)
      end

      it "re-renders the 'new' template" do
        post :create, {:raft_check => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested raft_check" do
        raft_check = RaftCheck.create! valid_attributes
        put :update, {:id => raft_check.to_param, :raft_check => new_attributes}, valid_session
        raft_check.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested raft_check as @raft_check" do
        raft_check = RaftCheck.create! valid_attributes
        put :update, {:id => raft_check.to_param, :raft_check => valid_attributes}, valid_session
        expect(assigns(:raft_check)).to eq(raft_check)
      end

      it "redirects to the raft_check" do
        raft_check = RaftCheck.create! valid_attributes
        put :update, {:id => raft_check.to_param, :raft_check => valid_attributes}, valid_session
        expect(response).to redirect_to(raft_check)
      end
    end

    describe "with invalid params" do
      it "assigns the raft_check as @raft_check" do
        raft_check = RaftCheck.create! valid_attributes
        put :update, {:id => raft_check.to_param, :raft_check => invalid_attributes}, valid_session
        expect(assigns(:raft_check)).to eq(raft_check)
      end

      it "re-renders the 'edit' template" do
        raft_check = RaftCheck.create! valid_attributes
        put :update, {:id => raft_check.to_param, :raft_check => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested raft_check" do
      raft_check = RaftCheck.create! valid_attributes
      expect {
        delete :destroy, {:id => raft_check.to_param}, valid_session
      }.to change(RaftCheck, :count).by(-1)
    end

    it "redirects to the raft_checks list" do
      raft_check = RaftCheck.create! valid_attributes
      delete :destroy, {:id => raft_check.to_param}, valid_session
      expect(response).to redirect_to(raft_checks_url)
    end
  end

end
