require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TsightingsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Tsighting. As you add validations to Tsighting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TsightingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tsightings as @tsightings" do
      tsighting = Tsighting.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:tsightings)).to eq([tsighting])
    end
  end

  describe "GET show" do
    it "assigns the requested tsighting as @tsighting" do
      tsighting = Tsighting.create! valid_attributes
      get :show, {:id => tsighting.to_param}, valid_session
      expect(assigns(:tsighting)).to eq(tsighting)
    end
  end

  describe "GET new" do
    it "assigns a new tsighting as @tsighting" do
      get :new, {}, valid_session
      expect(assigns(:tsighting)).to be_a_new(Tsighting)
    end
  end

  describe "GET edit" do
    it "assigns the requested tsighting as @tsighting" do
      tsighting = Tsighting.create! valid_attributes
      get :edit, {:id => tsighting.to_param}, valid_session
      expect(assigns(:tsighting)).to eq(tsighting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tsighting" do
        expect {
          post :create, {:tsighting => valid_attributes}, valid_session
        }.to change(Tsighting, :count).by(1)
      end

      it "assigns a newly created tsighting as @tsighting" do
        post :create, {:tsighting => valid_attributes}, valid_session
        expect(assigns(:tsighting)).to be_a(Tsighting)
        expect(assigns(:tsighting)).to be_persisted
      end

      it "redirects to the created tsighting" do
        post :create, {:tsighting => valid_attributes}, valid_session
        expect(response).to redirect_to(Tsighting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tsighting as @tsighting" do
        post :create, {:tsighting => invalid_attributes}, valid_session
        expect(assigns(:tsighting)).to be_a_new(Tsighting)
      end

      it "re-renders the 'new' template" do
        post :create, {:tsighting => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tsighting" do
        tsighting = Tsighting.create! valid_attributes
        put :update, {:id => tsighting.to_param, :tsighting => new_attributes}, valid_session
        tsighting.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested tsighting as @tsighting" do
        tsighting = Tsighting.create! valid_attributes
        put :update, {:id => tsighting.to_param, :tsighting => valid_attributes}, valid_session
        expect(assigns(:tsighting)).to eq(tsighting)
      end

      it "redirects to the tsighting" do
        tsighting = Tsighting.create! valid_attributes
        put :update, {:id => tsighting.to_param, :tsighting => valid_attributes}, valid_session
        expect(response).to redirect_to(tsighting)
      end
    end

    describe "with invalid params" do
      it "assigns the tsighting as @tsighting" do
        tsighting = Tsighting.create! valid_attributes
        put :update, {:id => tsighting.to_param, :tsighting => invalid_attributes}, valid_session
        expect(assigns(:tsighting)).to eq(tsighting)
      end

      it "re-renders the 'edit' template" do
        tsighting = Tsighting.create! valid_attributes
        put :update, {:id => tsighting.to_param, :tsighting => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tsighting" do
      tsighting = Tsighting.create! valid_attributes
      expect {
        delete :destroy, {:id => tsighting.to_param}, valid_session
      }.to change(Tsighting, :count).by(-1)
    end

    it "redirects to the tsightings list" do
      tsighting = Tsighting.create! valid_attributes
      delete :destroy, {:id => tsighting.to_param}, valid_session
      expect(response).to redirect_to(tsightings_url)
    end
  end

end
